-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj/hdlsrc/GammaCorrectionHDLExample/Pixel_Str_ip_src_Pixel_Stream_Gamma_Compensation_pkg.vhd
-- Created: 2017-11-05 13:15:12
-- 
-- Generated by MATLAB 9.2 and HDL Coder 3.10
-- 
-- -------------------------------------------------------------


LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

PACKAGE Pixel_Str_ip_src_Pixel_Stream_Gamma_Compensation_pkg IS
  TYPE vector_of_unsigned8 IS ARRAY (NATURAL RANGE <>) OF unsigned(7 DOWNTO 0);
END Pixel_Str_ip_src_Pixel_Stream_Gamma_Compensation_pkg;

